download_config:
  start_time: "2020-01-01"
  end_time: "2025-01-01"
  min_magnitude: 1.0
  max_magnitude: 9.0
  network: "CI"
  stations:
    - PAS
    - BSC
    - MAN
    - MAG
    - ABL  
    - AGM  
    - BAC  
    - BHP  
    - CFS  
    - DLA  
    - EML  
    - FMO  
    - GOR  
    - HYS  
    - IPT  
    - LAF  
    - MRS  
    - NWH  
    - SAN  
    - PDW
    - PTD
    - LVY
    - WRC2
    - BTP
    - BAI
    - SYN
    - JVA
    - Q0072
    - CPO
    - KRV3
    - SES
    - PLR
    - DGR
    - SDG
    - YUH2
    - BTL2
    - CRR
    - STG
    - FRM
    - RRX
    - CWC
    - JRC2
    - CYP
    - CLI2
    - BRE
    - MAN
    - PASC
    - SDD
  data_paths:
    raw_data: "../../../data/raw"

  output_file_name: "earthquake_data.parquet"
