download_config:
  start_time: "2020-01-01"
  end_time: "2025-01-01"
  min_magnitude: 1.0
  max_magnitude: 9.0
  network: "CI"
  stations:
    - PAS
    - BSC
    - LBT
    - DAX
    - PMO
    - HVL
    - ELK
    - PHX
    - CVD
    - MER
    - ION
    - SCS
    - KBR
    - MAN
    - SCL

  data_paths:
    raw_data: "../../../data/raw"

  output_file_name: "earthquake_data.parquet"
