features_config:
  # Path to the raw data (downloaded in the previous step).
  input_data_path: "data/raw/earthquake_data.parquet"

  # Where to save the feature table
  output_data_path: "data/features/earthquake_features.parquet"

  # Feature engineering parameters
  feature_params:
    rolling_depth_window: 5        # e.g., rolling window of 5 events for depth mean
    b_value_window: 50             # # of events to consider when computing b-value
    rolling_count_window: "30d"    # rolling time window for counting events
    rolling_mag_stats_window: "7d" # rolling time window for max magnitude, etc.

  # ETAS parameters (placeholder - adapt for real ETAS computations)
  etas_params:
    alpha: 1.0
    c: 0.01
    p: 1.1

  # Target creation params
  target_params:
    next_days_for_target: 30        # look-ahead window (days) for max magnitude
    # define magnitude bins if you want a multi-class approach
    magnitude_bin_edges: [2, 4, 6, 8, 10]

